### ISSUE TITLE
Create concept for level clustering and add level dynamically to overview screen

### ISSUE THREAD

**Issue by schlenger** [CodevemberTeam/codevember2019#13]
Right now the level overview screen needs be be adjusted by hand and is only supporting 10 levels. 

We could think of a pagination-like system to cluster the level from 1-10, 11-20 and so on. This could also include some basic GameMechanik blocks

**Comment by schlenger** [comment]
@BenediktBeuttler Is this finished now? I would like to skip the dynamical part since it's possible to create half-automated screenshots. IMHO we can close this issue

**Comment by BenediktBeuttler** [comment]
yes its finished IMHO. i close it.
