### ISSUE TITLE
(Multiple) Loops with increased difficulty

### ISSUE THREAD

**Issue by BenediktBeuttler** [CodevemberTeam/codevember2019#21]
After player finished all levels the first time, we can implement another run from level 1 (as it is implemented right now) but with different/ increased difficulty.

Following params need to be checked if applicable for adjustment and actually made adjustable:
- death threashold in lighcollisionbehaviour
- camera rotation speed
- fan rotation speed
- neon light movement speed
- schiebetür schneller

For visual aspect:
- post processing
- camera shake?

**Comment by BenediktBeuttler** [comment]
added threashold to globalgamesettings and adjust it when last level is finished. also mark the current run as finished (counter++).
todo: increase other difficulties
todo: make a ui element visible when 1 run is finished to allow manual selection of difficulty

**Comment by BenediktBeuttler** [comment]
btw its hard to adjust movement/rotation speed due to its value being variable in script and inspector....how to handle this one? @schlenger

**Comment by schlenger** [comment]
Basic loop: https://github.com/CodevemberTeam/codevember2019/commit/b22382cb7725c083b28739fe2d791dc9a4ce9e73

`Difficulty` -> `Story Loop` https://github.com/CodevemberTeam/codevember2019/commit/2b76a1e687a866f5432f0b22067dde1946762f59

Load Levels according to loop:
https://github.com/CodevemberTeam/codevember2019/commit/4d5aed945ee146a9f6019d7d5c3df8a3d42fe3fc

fyi @BenediktBeuttler
