### ISSUE TITLE
Setup lowquality settings

### ISSUE THREAD

**Issue by BenediktBeuttler** [CodevemberTeam/codevember2019#28]
what lowquality settings do we want to adjust?
- pixel light count
- shadow resolution
- soft/hard shadows (soft = hq, hard = lq)
...?

**Comment by BenediktBeuttler** [comment]
done.
any more ideas for params to adjust? @schlenger

**Comment by schlenger** [comment]
LQ:
- ShadowDistancce: 15
- Shadows: Hard (?)
- ShadwResolution: Low
- Anti Aliasing: Disabled

HQ:
- ShadowDistance 20
- Shadows: Hard + Soft
- ShadwResolution: Medium
- Anti Aliasing: 2x (?)

@BenediktBeuttler What do you think?
