### ISSUE TITLE
How does our game end?

### ISSUE THREAD

**Issue by BenediktBeuttler** [CodevemberTeam/codevember2019#34]
We need to think about what story do we want to tell and how do we finish the story arc?

My thoughts:
- rat tries to run away from the lab
- evil unknown person disguises as a good friend right until the first completed playthrough
- comes out he led the rat back to the starting point and also drugged the rat (mind is fucked up -> PP and harder lvls)
- rat still manages to escape

End:
- just simple text overlay + some credits?

**Comment by schlenger** [comment]
moved to: https://github.com/CodevemberTeam/codevember2019/issues/25
