### ISSUE TITLE
Allow fixed controls

### ISSUE THREAD

**Issue by schlenger** [CodevemberTeam/codevember2019#38]
Maybe think of an option in the settings? For example: use center of left/right half, depending on where the user clicked) as a fix point.

**Comment by schlenger** [comment]
Many people pointed that out. Also some people like the free controls.

Maybe we could offer a short selection screen on which you can chose. This option should be also available later on in the settings

@BenediktBeuttler Any further ideas?

**Comment by BenediktBeuttler** [comment]
close to finish, some minor tweaks. needs to be checked

**Comment by schlenger** [comment]
I've cleaned up everything with https://github.com/CodevemberTeam/codevember2019/commit/569d36dbdd65fafbff4af80f56ec48d67cdf82bb and the left and right support with https://github.com/CodevemberTeam/codevember2019/commit/4ab62fdb7a497e2c9c30cf34422d86eb0e6c04cc
