### ISSUE TITLE
Enhancement Ideas from Store-Reviews

### ISSUE THREAD

**Issue by BenediktBeuttler** [CodevemberTeam/codevember2019#45]
- make it longer in general
- controls are confusing
- stuck on walls, cannot move when hitting a wall
- mehr mystery??
"I’m wondering though, the computer (Chuck) mentioned finding a mainframe and I was wondering if that’s a real thing you can find in the game as like an Easter egg or I’m you’re just supposed to finish all the levels? Is there any more to the game? Anything secret?"
- story needs to make more sense, put more weight on it:
"First of all why is there a computer and why is it helping the rat to escape? That was the first question that came into my mind. When I progressed more into the levels they all don’t add up. First thing the computer, and second the rat being literate,  and third the CCTV trying to find a rat. If the whole objective was that, for example: “A guy lost his pet rat and then found out that he was taken to the animal lab, however the guy have to sneak in to get the rat out without being spotted” (terrible storyline) then the CCTV and the literacy and the computer will add up. Don’t get me wrong, it’s a decent game but there are several things that needs to filled in order for the game to be interesting. "

**Comment by schlenger** [comment]
Discussionn moved to internal doc
