### ISSUE TITLE
Check for typos

### ISSUE THREAD

**Issue by schlenger** [CodevemberTeam/codevember2019#50]
... due to the fact that there are some...

**Comment by schlenger** [comment]
Would be nice to have this done with https://github.com/CodevemberTeam/codevember2019/issues/51, but this could be quite some effort

**Comment by schlenger** [comment]
> In the last level one screen message had a typo "stay (save) little rat, i'll miss you". It should be (safe).

**Comment by BenediktBeuttler** [comment]
fixed typo save to safe in last level  with commit [9e54e68d](https://github.com/CodevemberTeam/codevember2019/commit/9e54e68d2b953df9b61f8e936308a86673b91ede)

**Comment by schlenger** [comment]
I think the most typos in the screens should be fixed with https://github.com/CodevemberTeam/codevember2019/pull/57

However, I'll give the complete dialogs in review :)
