### ISSUE TITLE
Move dialog loading to json implementation

### ISSUE THREAD

**Issue by schlenger** [CodevemberTeam/codevember2019#51]
This could be helpful if we want to improve the story or fix typos easily. We need to check the effort and test this for all operating systems.

**Comment by BenediktBeuttler** [comment]
an easier and faster solution would be to use the playerpref-environment. 
PlayerPrefs.SetString can hold at least up to 1 MB before crashing, which are over 200 pages of plain text (if its stored as plain text).

**Comment by schlenger** [comment]
Mhh since this is static and not dynamic, we can move it directly to a data class. Would be the easiest solution for now - didn't think of this before. I'll take care
